# Generated by Django 4.1 on 2022-11-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skills'),
        ('projects', '0005_alter_projects_options_reviews_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
